import 'dart:io';
import 'dart:async';
import 'dart:typed_data';

import 'package:dio/dio.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:kingclub/src/core/media/media_cache.dart';

class _Transport implements HttpClientAdapter {
  int calls = 0;
  @override
  Future<ResponseBody> fetch(
    RequestOptions options,
    Stream<Uint8List>? stream,
    Future<void>? cancel,
  ) async {
    calls++;
    await Future<void>.delayed(const Duration(milliseconds: 10));
    return ResponseBody.fromBytes(
      List.filled(8, 7),
      200,
      headers: {
        'content-length': ['8'],
        'content-type': ['image/png'],
      },
    );
  }

  @override
  void close({bool force = false}) {}
}

void main() {
  late Directory dir;
  late _Transport transport;
  late MediaCache cache;
  setUp(() async {
    dir = await Directory.systemTemp.createTemp('kingclub-media-test-');
    transport = _Transport();
    cache = MediaCache(
      directory: () async => dir,
      dio: Dio()..httpClientAdapter = transport,
      imageBudget: 16,
    );
  });
  tearDown(() async {
    if (await dir.exists()) await dir.delete(recursive: true);
  });
  test('clear rejects an old request paused before cache lookup', () async {
    final cached = await cache.get(
      'https://media.example.test/voice',
      scope: 'member:a',
      contentKey: 'voice',
      kind: MediaKind.audio,
    );
    final started = Completer<void>(), release = Completer<void>();
    var reads = 0;
    final reopened = MediaCache(
      directory: () async {
        if (++reads == 1) {
          started.complete();
          await release.future;
        }
        return dir;
      },
      dio: Dio()..httpClientAdapter = transport,
    );
    final pending = reopened.get(
      'https://media.example.test/voice',
      scope: 'member:a',
      contentKey: 'voice',
      kind: MediaKind.audio,
    );
    final check = expectLater(pending, throwsStateError);
    await started.future;
    final clearing = reopened.clear(privateOnly: true);
    release.complete();
    await check;
    await clearing;
    expect(await cached.exists(), false);
    expect(transport.calls, 1);
  });
  test('clear immediately after get cancels before network starts', () async {
    final pending = cache.get(
      'https://media.example.test/voice',
      scope: 'member:a',
      contentKey: 'voice',
      kind: MediaKind.audio,
    );
    final check = expectLater(pending, throwsStateError);
    await cache.clear(privateOnly: true);
    await check;
    expect(transport.calls, 0);
  });
  test(
    'eviction removes only matching account audio and retry downloads',
    () async {
      Future<File> load(String account) => cache.get(
        'https://media.example.test/voice',
        scope: account,
        contentKey: 'voice',
        kind: MediaKind.audio,
      );
      final first = await load('member:a');
      final other = await load('member:b');
      await cache.evict(
        scope: 'member:a',
        contentKey: 'voice',
        kind: MediaKind.audio,
      );
      expect(await first.exists(), false);
      expect(await other.exists(), true);
      await load('member:a');
      expect(transport.calls, 3);
    },
  );
  test(
    'video posters persist, deduplicate and isolate account scopes',
    () async {
      var decodes = 0;
      Future<Uint8List?> decode(File source) async {
        expect(await source.exists(), true);
        decodes++;
        return Uint8List.fromList([1, 2, 3]);
      }

      Future<File> load(String scope) => cache.videoPoster(
        'https://media.example.test/video',
        scope: scope,
        contentKey: 'video-1',
        decode: decode,
      );
      final files = await Future.wait([load('member:a'), load('member:a')]);
      expect(files[0].path, files[1].path);
      await load('member:a');
      expect(decodes, 1);
      expect(transport.calls, 1);
      final second = await load('member:b');
      expect(second.path, isNot(files[0].path));
      expect(decodes, 2);
      await cache.clear(privateOnly: true);
      expect(await files[0].exists(), false);
      expect(await second.exists(), false);
    },
  );
  test(
    'clearing during poster decoding discards late generated bytes',
    () async {
      final started = Completer<void>();
      final decoded = Completer<Uint8List?>();
      final pending = cache.videoPoster(
        'https://media.example.test/video',
        scope: 'member:a',
        contentKey: 'video-1',
        decode: (_) {
          started.complete();
          return decoded.future;
        },
      );
      final assertion = expectLater(pending, throwsStateError);
      await started.future;
      final clearing = cache.clear(privateOnly: true);
      decoded.complete(Uint8List.fromList([1, 2, 3]));
      await assertion;
      await clearing;
      expect(await cache.sizeBytes(), 0);
    },
  );
  test(
    'deduplicates requests, reuses persisted media and rotated URLs',
    () async {
      final files = await Future.wait(
        List.generate(
          4,
          (_) => cache.get(
            'https://media.example.test/file?token=a',
            scope: 'member:a',
            contentKey: 'photo-v1',
          ),
        ),
      );
      expect(transport.calls, 1);
      expect(files.map((f) => f.path).toSet().length, 1);
      final reopened = MediaCache(
        directory: () async => dir,
        dio: Dio()..httpClientAdapter = transport,
      );
      await reopened.get(
        'https://media.example.test/file?token=b',
        scope: 'member:a',
        contentKey: 'photo-v1',
      );
      expect(transport.calls, 1);
      await cache.get(
        'https://media.example.test/file?token=b',
        scope: 'member:b',
        contentKey: 'photo-v1',
      );
      expect(transport.calls, 2);
    },
  );
  test(
    'evicts old media under budget and clears private data separately',
    () async {
      final first = await cache.get(
        'https://media.example.test/1',
        scope: 'public',
      );
      await cache.get('https://media.example.test/2', scope: 'member:a');
      final last = await cache.get(
        'https://media.example.test/3',
        scope: 'public',
      );
      expect(await cache.sizeBytes(), 16);
      expect(await first.exists(), false);
      await cache.clear(privateOnly: true);
      expect(await last.exists(), true);
      expect(await cache.sizeBytes(), 8);
      await cache.clear();
      expect(await cache.sizeBytes(), 0);
    },
  );
  test('version changes redownload and insecure links are rejected', () async {
    await cache.get(
      'https://media.example.test/a',
      scope: 'public',
      contentKey: 'v1',
    );
    await cache.get(
      'https://media.example.test/a',
      scope: 'public',
      contentKey: 'v2',
    );
    expect(transport.calls, 2);
    await expectLater(
      cache.get('http://media.example.test/a', scope: 'public'),
      throwsFormatException,
    );
  });
}
